// Copyright (c) 2023 Juan M. G. de Agüero

#include "Test/TestAdd.hpp"
#include "Test/TestBackward.hpp"
#include "Test/TestBroadcast.hpp"
#include "Test/TestCrossEntropy.hpp"
#include "Test/TestExp.hpp"
#include "Test/TestGather.hpp"
#include "Test/TestIndex.hpp"
#include "Test/TestMax.hpp"
#include "Test/TestMM.hpp"
#include "Test/TestMul.hpp"
#include "Test/TestReLU.hpp"
#include "Test/TestSum.hpp"
#include "Test/TestUnsqueeze.hpp"